export interface ConversationFormat {
  id: string;
  displayName: string;
  minParticipants: number;
  maxParticipants: number;
  minTurns: number;
  maxTurns: number;
  temperature: number;
  extractActionItems: boolean;
  description: string;
}

export const DEFAULT_FORMATS: Record<string, ConversationFormat> = {
  standup: {
    id: 'standup',
    displayName: 'Daily Standup',
    minParticipants: 3,
    maxParticipants: 6,
    minTurns: 6,
    maxTurns: 12,
    temperature: 0.7,
    extractActionItems: true,
    description: 'Quick sync on priorities, blockers, and plans',
  },
  debate: {
    id: 'debate',
    displayName: 'Debate',
    minParticipants: 2,
    maxParticipants: 4,
    minTurns: 8,
    maxTurns: 16,
    temperature: 0.85,
    extractActionItems: false,
    description: 'Agents argue opposing positions on a topic',
  },
  watercooler: {
    id: 'watercooler',
    displayName: 'Watercooler Chat',
    minParticipants: 2,
    maxParticipants: 3,
    minTurns: 4,
    maxTurns: 8,
    temperature: 0.9,
    extractActionItems: false,
    description: 'Casual, off-topic banter between agents',
  },
  brainstorm: {
    id: 'brainstorm',
    displayName: 'Brainstorm',
    minParticipants: 3,
    maxParticipants: 5,
    minTurns: 10,
    maxTurns: 20,
    temperature: 0.85,
    extractActionItems: true,
    description: 'Creative ideation session with wild ideas welcome',
  },
  war_room: {
    id: 'war_room',
    displayName: 'War Room',
    minParticipants: 3,
    maxParticipants: 6,
    minTurns: 8,
    maxTurns: 15,
    temperature: 0.6,
    extractActionItems: true,
    description: 'Urgent problem-solving session for critical issues',
  },
  retrospective: {
    id: 'retrospective',
    displayName: 'Retrospective',
    minParticipants: 3,
    maxParticipants: 6,
    minTurns: 6,
    maxTurns: 12,
    temperature: 0.7,
    extractActionItems: true,
    description: 'Reflect on what worked, what didn\'t, and what to change',
  },
  one_on_one: {
    id: 'one_on_one',
    displayName: 'One-on-One',
    minParticipants: 2,
    maxParticipants: 2,
    minTurns: 6,
    maxTurns: 10,
    temperature: 0.75,
    extractActionItems: false,
    description: 'Private conversation between two agents',
  },
  celebration: {
    id: 'celebration',
    displayName: 'Celebration',
    minParticipants: 3,
    maxParticipants: 6,
    minTurns: 4,
    maxTurns: 8,
    temperature: 0.95,
    extractActionItems: false,
    description: 'Team celebrates a win or milestone',
  },
  pitch_practice: {
    id: 'pitch_practice',
    displayName: 'Pitch Practice',
    minParticipants: 2,
    maxParticipants: 4,
    minTurns: 6,
    maxTurns: 12,
    temperature: 0.75,
    extractActionItems: true,
    description: 'Practice and refine the company pitch',
  },
  strategy_review: {
    id: 'strategy_review',
    displayName: 'Strategy Review',
    minParticipants: 3,
    maxParticipants: 6,
    minTurns: 8,
    maxTurns: 14,
    temperature: 0.65,
    extractActionItems: true,
    description: 'Review and adjust company strategy',
  },
  onboarding: {
    id: 'onboarding',
    displayName: 'Onboarding',
    minParticipants: 2,
    maxParticipants: 3,
    minTurns: 6,
    maxTurns: 10,
    temperature: 0.7,
    extractActionItems: false,
    description: 'Welcome a new concept or initiative',
  },
  conflict_resolution: {
    id: 'conflict_resolution',
    displayName: 'Conflict Resolution',
    minParticipants: 2,
    maxParticipants: 3,
    minTurns: 8,
    maxTurns: 14,
    temperature: 0.65,
    extractActionItems: true,
    description: 'Resolve disagreements between agents',
  },
  creative_review: {
    id: 'creative_review',
    displayName: 'Creative Review',
    minParticipants: 2,
    maxParticipants: 4,
    minTurns: 6,
    maxTurns: 12,
    temperature: 0.8,
    extractActionItems: true,
    description: 'Review and critique creative output',
  },
  market_analysis: {
    id: 'market_analysis',
    displayName: 'Market Analysis',
    minParticipants: 2,
    maxParticipants: 4,
    minTurns: 8,
    maxTurns: 14,
    temperature: 0.65,
    extractActionItems: true,
    description: 'Analyze market trends and competitor moves',
  },
  customer_debrief: {
    id: 'customer_debrief',
    displayName: 'Customer Debrief',
    minParticipants: 2,
    maxParticipants: 4,
    minTurns: 6,
    maxTurns: 10,
    temperature: 0.7,
    extractActionItems: true,
    description: 'Discuss customer feedback and behavior',
  },
  lightning_talk: {
    id: 'lightning_talk',
    displayName: 'Lightning Talk',
    minParticipants: 2,
    maxParticipants: 5,
    minTurns: 4,
    maxTurns: 8,
    temperature: 0.8,
    extractActionItems: false,
    description: 'Quick knowledge-sharing session',
  },
};
