import chalk from 'chalk';
import { AgentConfig } from './agent-generator.js';
import { WorkerConfig } from './worker-generator.js';

export interface GeneratedConfigs {
  'agents.json': object;
  'policies.json': object;
  'triggers.json': object;
  'conversations.json': object;
  'step-registry.json': object;
  'seed.sql': string;
}

export function generateConfigs(
  startupName: string,
  agentConfig: AgentConfig,
  workerConfig: WorkerConfig,
): GeneratedConfigs {
  console.log(chalk.dim('  Step 4/4: Generating config files...'));

  const agentsJson = {
    version: '1.0',
    startup: startupName,
    agents: agentConfig.agents.map((a) => ({
      id: a.id,
      displayName: a.displayName,
      role: a.role,
      tone: a.tone,
      systemDirective: a.systemDirective,
      quirk: a.quirk,
      canInitiate: a.canInitiate,
      cooldownHours: a.cooldownHours,
    })),
    conversationFormats: agentConfig.conversationFormats,
    dailySchedule: agentConfig.dailySchedule,
  };

  const policiesJson = {
    version: '1.0',
    ...workerConfig.policies,
    cap_gates: workerConfig.capGates,
  };

  const triggersJson = {
    version: '1.0',
    triggers: workerConfig.triggers,
  };

  const conversationsJson = {
    version: '1.0',
    formats: Object.fromEntries(
      agentConfig.conversationFormats.map((f) => [
        f,
        getDefaultFormatConfig(f),
      ]),
    ),
  };

  const stepRegistryJson = {
    version: '1.0',
    steps: Object.fromEntries(
      workerConfig.stepKinds.map((sk) => [
        sk.kind,
        {
          displayName: sk.displayName,
          workerType: sk.workerType,
          description: sk.description,
          requiredConfig: sk.requiredConfig,
          capGatePolicyKey: sk.capGatePolicyKey ?? null,
        },
      ]),
    ),
  };

  const seedSql = generateSeedSQL(startupName, agentConfig, workerConfig);

  console.log(chalk.green('  ✓ All config files generated'));
  console.log('');

  return {
    'agents.json': agentsJson,
    'policies.json': policiesJson,
    'triggers.json': triggersJson,
    'conversations.json': conversationsJson,
    'step-registry.json': stepRegistryJson,
    'seed.sql': seedSql,
  };
}

function getDefaultFormatConfig(format: string) {
  const defaults: Record<string, object> = {
    standup: {
      minParticipants: 3, maxParticipants: 6, minTurns: 6, maxTurns: 12,
      temperature: 0.7, extractActionItems: true,
    },
    debate: {
      minParticipants: 2, maxParticipants: 4, minTurns: 8, maxTurns: 16,
      temperature: 0.85, extractActionItems: false,
    },
    watercooler: {
      minParticipants: 2, maxParticipants: 3, minTurns: 4, maxTurns: 8,
      temperature: 0.9, extractActionItems: false,
    },
    brainstorm: {
      minParticipants: 3, maxParticipants: 5, minTurns: 10, maxTurns: 20,
      temperature: 0.85, extractActionItems: true,
    },
    war_room: {
      minParticipants: 3, maxParticipants: 6, minTurns: 8, maxTurns: 15,
      temperature: 0.6, extractActionItems: true,
    },
    retrospective: {
      minParticipants: 3, maxParticipants: 6, minTurns: 6, maxTurns: 12,
      temperature: 0.7, extractActionItems: true,
    },
    one_on_one: {
      minParticipants: 2, maxParticipants: 2, minTurns: 6, maxTurns: 10,
      temperature: 0.75, extractActionItems: false,
    },
    celebration: {
      minParticipants: 3, maxParticipants: 6, minTurns: 4, maxTurns: 8,
      temperature: 0.95, extractActionItems: false,
    },
  };
  return defaults[format] ?? {
    minParticipants: 2, maxParticipants: 4, minTurns: 6, maxTurns: 12,
    temperature: 0.7, extractActionItems: false,
  };
}

function generateSeedSQL(
  startupName: string,
  agentConfig: AgentConfig,
  workerConfig: WorkerConfig,
): string {
  const lines: string[] = [
    `-- Seed data for ${startupName}`,
    `-- Generated by Hatchery`,
    '',
    '-- Policies',
  ];

  const policies = {
    auto_approve: workerConfig.policies.auto_approve,
    daily_quotas: workerConfig.policies.daily_quotas,
    memory_influence: workerConfig.policies.memory_influence,
    ...Object.fromEntries(
      Object.entries(workerConfig.capGates).map(([k, v]) => [`cap_gate_${k}`, v]),
    ),
  };

  for (const [key, value] of Object.entries(policies)) {
    lines.push(
      `INSERT INTO ops_policies (key, value, description) VALUES ('${key}', '${JSON.stringify(value)}', 'Auto-generated') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;`,
    );
  }

  lines.push('', '-- Step Registry');
  for (const sk of workerConfig.stepKinds) {
    lines.push(
      `INSERT INTO ops_step_registry (kind, display_name, worker_type, required_config, cap_gate_policy_key) VALUES ('${sk.kind}', '${sk.displayName}', '${sk.workerType}', ARRAY[${sk.requiredConfig.map((c) => `'${c}'`).join(',')}], ${sk.capGatePolicyKey ? `'cap_gate_${sk.capGatePolicyKey}'` : 'NULL'}) ON CONFLICT (kind) DO UPDATE SET display_name = EXCLUDED.display_name;`,
    );
  }

  lines.push('', '-- Triggers');
  for (const trigger of workerConfig.triggers) {
    lines.push(
      `INSERT INTO ops_triggers (name, event_pattern, condition, proposal_template, cooldown_minutes, is_active) VALUES ('${trigger.name}', '${trigger.eventPattern}', '${JSON.stringify(trigger.condition ?? {})}', '${JSON.stringify(trigger.proposalTemplate)}', ${trigger.cooldownMinutes}, ${trigger.isActive});`,
    );
  }

  lines.push('', '-- Initial Relationships');
  for (const rel of agentConfig.initialAffinities) {
    lines.push(
      `INSERT INTO ops_relationships (agent_a, agent_b, affinity, total_interactions, positive_interactions, negative_interactions, drift_log) VALUES ('${rel.agentA}', '${rel.agentB}', ${rel.affinity}, 0, 0, 0, '[]') ON CONFLICT (agent_a, agent_b) DO UPDATE SET affinity = EXCLUDED.affinity;`,
    );
  }

  lines.push('');
  return lines.join('\n');
}
