import type { AgentConfig, WorkerConfig } from './types';

export function generateSeedSql(
  startupName: string,
  agentConfig: AgentConfig,
  workerConfig: WorkerConfig,
): string {
  const lines: string[] = [
    `-- Seed data for ${startupName}`,
    '-- Generated by Hatchery',
    '',
    '-- Policies',
  ];

  const policyMap: Record<string, unknown> = {
    auto_approve: workerConfig.policies.auto_approve,
    daily_quotas: workerConfig.policies.daily_quotas,
    memory_influence: workerConfig.policies.memory_influence,
    agent_configs: {
      version: '1.0',
      startup: startupName,
      agents: agentConfig.agents,
      conversationFormats: agentConfig.conversationFormats,
      dailySchedule: agentConfig.dailySchedule,
    },
    ...Object.fromEntries(
      Object.entries(workerConfig.capGates).map(([key, value]) => [`cap_gate_${key}`, value]),
    ),
  };

  for (const [key, value] of Object.entries(policyMap)) {
    lines.push(
      `INSERT INTO ops_policies (key, value, description) VALUES ('${escapeSQL(key)}', '${escapeSQL(JSON.stringify(value))}', 'Auto-generated') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;`,
    );
  }

  lines.push('', '-- Step Registry');
  for (const sk of workerConfig.stepKinds) {
    const requiredConfigArray = sk.requiredConfig.map((c) => `'${escapeSQL(c)}'`).join(',');
    const capGatePolicyKey = sk.capGatePolicyKey
      ? `'${escapeSQL(`cap_gate_${sk.capGatePolicyKey}`)}'`
      : 'NULL';

    lines.push(
      `INSERT INTO ops_step_registry (kind, display_name, worker_type, description, required_config, cap_gate_policy_key) VALUES ('${escapeSQL(sk.kind)}', '${escapeSQL(sk.displayName)}', '${escapeSQL(sk.workerType)}', '${escapeSQL(sk.description)}', ARRAY[${requiredConfigArray}], ${capGatePolicyKey}) ON CONFLICT (kind) DO UPDATE SET display_name = EXCLUDED.display_name, description = EXCLUDED.description;`,
    );
  }

  lines.push('', '-- Triggers');
  for (const trigger of workerConfig.triggers) {
    lines.push(
      `INSERT INTO ops_triggers (name, event_pattern, condition, proposal_template, cooldown_minutes, is_active) VALUES ('${escapeSQL(trigger.name)}', '${escapeSQL(trigger.eventPattern)}', '${escapeSQL(JSON.stringify(trigger.condition ?? {}))}', '${escapeSQL(JSON.stringify(trigger.proposalTemplate))}', ${trigger.cooldownMinutes}, ${trigger.isActive});`,
    );
  }

  lines.push('', '-- Initial Relationships');
  for (const rel of agentConfig.initialAffinities) {
    const [agentA, agentB] = [rel.agentA, rel.agentB].sort();
    lines.push(
      `INSERT INTO ops_relationships (agent_a, agent_b, affinity, total_interactions, positive_interactions, negative_interactions, drift_log) VALUES ('${escapeSQL(agentA)}', '${escapeSQL(agentB)}', ${rel.affinity}, 0, 0, 0, '[]') ON CONFLICT (agent_a, agent_b) DO UPDATE SET affinity = EXCLUDED.affinity;`,
    );
  }

  lines.push('');
  return lines.join('\n');
}

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}
